name: vocode-telegram-bot
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - openssl=1.1.1w
  - portaudio
  - ffmpeg
  - git
  - pip
  - pip:
    # Installing vocode from the git repository
    # Installing vocode from a specific branch of the git repository
    - vocode
    - python-dotenv
    - ipython
    - deepgram-sdk
    - poetry
    - python-telegram-bot
    - langchainhub
    - google-cloud-texttospeech==2.16.1
    - azure-cognitiveservices-speech==1.31.0